server:
  port: 8888
spring:
  application:
    name: gateway

  cloud:
    consul:
      host: 172.21.245.205
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}
        service-name: gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#      routes:
#        - id: account-service
#          uri: lb://account-service
#          predicates:
#            - Path=/api/accounts/**, /api/roles/**, /api/privileges/**, /api/refreshToken/**
#        - id: client-service
#          uri: lb://client-service
#          predicates:
#            - Path=/api/profiles/**
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/products/**


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http: DEBUG

