spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/tch_tech
    username: root
    password: marc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
#  cloud:
#    consul:
#      host: localhost
#      discovery:
#        enabled: false
#      port: 8500

server:
  port: 8085